import{a as u,S as g,i as m}from"./assets/vendor-91c99ba8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const h="https://api.thecatapi.com/v1",y=`${h}/breeds`,l="cat_breeds",d="cat_by_breed",f={}.CAT_API_KEY;function E(){const t=localStorage.getItem(l);if(t){const e=JSON.parse(t);return console.log("[fetchBreeds] cachedCatBreeds: ",e),JSON.parse(e)}return u.get(`${y}`,{headers:{API_KEY_HEADER:f}}).then(e=>(localStorage.setItem(l,JSON.stringify(e.data)),console.log("[fetchBreeds] response: ",e),e.data))}function S(t){const e=localStorage.getItem(d);if(e){const n=JSON.parse(e);return console.log("[fetchCatByBreed] cachedCatByBreed: ",n),JSON.parse(n)}return u.get(`${{headers:{API_KEY_HEADER:f}}}breed_ids=${t}`).then(n=>(localStorage.setItem(d,JSON.stringify(n.data)),console.log("[fetchCatByBreed] response: ",n),n.data))}function c(t,e){t.classList.toggle("is-hidden-compeletely",!e)}function _(t,e,n){E().then(function(s){t.classList.remove("is-invisible");const r=s.map(({id:o,name:i})=>`<option value="${o}">${i}</option>`);t.insertAdjacentHTML("afterbegin",r.join("")),new g({select:t})}).catch(function(s){p(s)}).finally(function(){c(t,!0),c(e,!1),c(n,!0)})}function B(t,e,n,s){c(s,!1),c(n,!0),c(e,!0);const r=t.currentTarget.value;S(r).then(function(o){if(console.log("catData: ",o),o.length===0){s.innerHTML="";return}let{url:i,breeds:a}=o[0];s.innerHTML=`
        <img src="${i}" alt="${a[0].name}" width="400" loading="lazy" />
        <div class="text-box">
          <h2>${a[0].name}</h2>
          <p>${a[0].description}</p>
          <p><b>Temperament: </b>${a[0].temperament}</p>
          <p><b>Origin: </b>${a[0].origin}</p>
        </div>`}).catch(function(o){p(o)}).finally(function(){c(n,!1),c(e,!0),c(s,!0)})}function p(t){m.error({title:"🔻 Oops!",message:t.message??"Something went wrong!",position:"topCenter"})}(()=>{const t=document.querySelector(".breed-select"),e=document.querySelector(".loader"),n=document.querySelector(".cat-description");t.addEventListener("change",s=>B(s,t,e,n)),_(t,e,n)})();
//# sourceMappingURL=commonHelpers.js.map
