import{a as l,S as f,i as p}from"./assets/vendor-91c99ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=i(t);fetch(t.href,n)}})();const u="https://api.thecatapi.com/v1",m=`${u}/breeds`,g=`${u}/images/search?`;l.defaults.headers.common["x-api-key"]={}.CAT_API_KEY;function h(){return l.get(`${m}`).then(e=>e.data)}function y(e){return l.get(`${g}breed_ids=${e}`).then(r=>r.data)}function s(e,r){e.classList.toggle("is-hidden-compeletely",!r)}function b(e,r,i){h().then(function(o){e.classList.remove("is-invisible");const t=o.map(({id:n,name:c})=>`<option value="${n}">${c}</option>`);e.insertAdjacentHTML("afterbegin",t.join("")),new f({select:e})}).catch(function(o){d(o)}).finally(function(){s(e,!0),s(r,!1),s(i,!0)})}function $(e,r,i,o){s(o,!1),s(i,!0),s(r,!0);const t=e.currentTarget.value;y(t).then(function(n){n.length===0&&(o.innerHTML="");const{url:c,breeds:a}=n[0];o.innerHTML=`
        <img src="${c}" alt="${a[0].name}" width="400" loading="lazy" />
        <div class="text-box">
          <h2>${a[0].name}</h2>
          <p>${a[0].description}</p>
          <p><b>Temperament: </b>${a[0].temperament}</p>
          <p><b>Origin: </b>${a[0].origin}</p>
        </div>`}).catch(function(n){d(n)}).finally(function(){s(i,!1),s(r,!0),s(o,!0)})}function d(e){p.error({title:"🔻 Oops!",message:e.message??"Something went wrong!",position:"topCenter"})}(()=>{const e=document.querySelector(".breed-select"),r=document.querySelector(".loader"),i=document.querySelector(".cat-description");e.addEventListener("change",o=>$(o,e,r,i)),b(e,r,i)})();
//# sourceMappingURL=commonHelpers.js.map
